[package]
name = "boa_scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
boa_engine = "0.20.0"
boa_runtime = "0.20.0"
pollster = "0.4.0"
serde = { version = "1.0.217", features = ["serde_derive"] }
serde_json = "1.0.138"
